package lhexanome.optimodlivraison.ui.panel;

import lhexanome.optimodlivraison.ui.controller.MainController;

import javax.swing.*;
import java.awt.*;

public class MainPanel extends AbstractPanel {
    private JPanel contentPane;
    private JPanel wrapperPanel;
    private JPanel roadMapPanel;
    private JPanel deliveryOrderPanel;
    private JPanel tourPanel;

    public MainPanel(MainController controller,
                     JPanel roadMapPanel,
                     JPanel deliveryOrderPanel,
                     JPanel tourPanel) {
        super(controller);
        this.roadMapPanel = roadMapPanel;
        this.deliveryOrderPanel = deliveryOrderPanel;
        this.tourPanel = tourPanel;
        setup();
    }

    @Override
    public void setup() {
        GridBagConstraints gbc = new GridBagConstraints();

        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.8;
        gbc.weighty = 1;
        gbc.fill = GridBagConstraints.BOTH;
        wrapperPanel.add(roadMapPanel, gbc);

        gbc.weightx = 0.2;
        gbc.gridx = 1;
        wrapperPanel.add(deliveryOrderPanel, gbc);

        gbc.weighty = 0.2;
        gbc.gridy = 1;
        wrapperPanel.add(tourPanel, gbc);
    }

    @Override
    public JPanel getContentPane() {
        return contentPane;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        wrapperPanel = new JPanel();
        wrapperPanel.setLayout(new GridBagLayout());
        contentPane.add(wrapperPanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
