package lhexanome.optimodlivraison.ui.panel;

import lhexanome.optimodlivraison.platform.models.Tour;
import lhexanome.optimodlivraison.ui.controller.ControllerInterface;

import javax.swing.*;
import java.awt.*;

/**
 * Panel used to edit a tour.
 */
public class TourEditorPanel extends AbstractPanel {
    /**
     * Content pane.
     */
    private JPanel contentPane;
    private Tour tour;

    /**
     * Initialize a panel with a panel.
     *
     * @param controller Controller linked to the panel
     */
    public TourEditorPanel(ControllerInterface controller) {
        super(controller);
    }

    /**
     * Initialization function.
     * WARNING: This function is not called by the constructor.
     * You have to call it after calling super() !
     * Explications : Intellij GUI designer use an initializer block to initialize components,
     * But the initializer block is called after the super() method.
     */
    @Override
    public void setup() {

    }

    /**
     * Return the content panel.
     * The field is created by Intellij and must be declared in the child panel
     *
     * @return Content pane
     */
    @Override
    public JPanel getContentPane() {
        return contentPane;
        //CHECKSTYLE:OFF
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridBagLayout());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    public void setTour(Tour tour) {
        this.tour = tour;
    }
}
