package lhexanome.optimodlivraison.ui.netbeanpanel;

import lhexanome.optimodlivraison.platform.models.Delivery;
import lhexanome.optimodlivraison.platform.models.RoadMap;

import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.Set;

/**
 * @author hugues
 * CHECKSTYLE:OFF
 */
public class DeliveryPanel extends javax.swing.JPanel {

    private Delivery delivery;
    private RoadMap roadMap;
    private int number;

    /**
     * Creates new form orderItem
     *
     * @param delivery delivery
     */

    public DeliveryPanel(Delivery delivery, RoadMap roadMap) {
        this.delivery = delivery;
        this.roadMap = roadMap;
        this.number = -1;
        initComponents();
    }


    /**
     * @return
     */
    private String getTextAdresse() {
        return "adresse : " + delivery.getIntersection().getId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelHoraire = new javax.swing.JLabel();
        jLabelAdresse = new javax.swing.JLabel();
        jLabelTimeSlot = new javax.swing.JLabel();
        jLabelNumber = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));

        setLayout(new java.awt.GridBagLayout());
        /*
        jLabelHoraire.setText("08:56 - 09:36");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabelHoraire, gridBagConstraints);
        */

        jLabelAdresse.setText(getTextAdresse());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabelAdresse, gridBagConstraints);

        int gridY = 3;
        if (delivery.getSlot() != null) {
            jLabelTimeSlot.setText(getTextTimeSlot());
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 3;
            gridBagConstraints.gridy = gridY;
            gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
            add(jLabelTimeSlot, gridBagConstraints);
            gridY++;
        }

        for (String streat : getStreats()) {
            JLabel streatLabel = new JLabel();
            streatLabel.setText(streat);
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 3;
            gridBagConstraints.gridy = gridY;
            gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
            add(streatLabel, gridBagConstraints);
            gridY++;
        }

        if (gridY < 10) gridY = 10;
        JSeparator jSeparator1 = new JSeparator();
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = gridY;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jSeparator1, gridBagConstraints);

        jLabelNumber.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelNumber.setText(number < 0 ? "O" : number + "");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabelNumber, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        add(filler2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(filler3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(filler4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        add(filler5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        add(filler6, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JLabel jLabelAdresse;
    private javax.swing.JLabel jLabelHoraire;
    private javax.swing.JLabel jLabelNumber;
    private javax.swing.JLabel jLabelTimeSlot;

    public String getTextTimeSlot() {
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
        return "de " + sdf.format(delivery.getSlot().getStart()) + " à " + sdf.format(delivery.getSlot().getEnd());
    }

    private Set<String> getStreats() {
        Set<String> res = new HashSet<>();
        roadMap.getTronconsFromIntersection(delivery.getIntersection()).forEach(vector -> {
            res.add(vector.getNameStreet().isEmpty() ? "rue sans nom" : vector.getNameStreet());
        });
        return res;
    }
    // End of variables declaration//GEN-END:variables
}
