package lhexanome.optimodlivraison.ui.netbeanpanel;

import lhexanome.optimodlivraison.platform.models.Delivery;

import java.awt.*;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 *
 * @author hugues
 */
public class DeliveryListPanel extends javax.swing.JPanel {

    private Map<Delivery,DeliveryPanel> panelsDeliverys;
    private List<Delivery> deliveries;
    /**
     * Creates new form DeliveryListPanel
     */
    public DeliveryListPanel(Set<Delivery> deliveries) {
        panelsDeliverys = new HashMap<>();
        for(Delivery delivery : deliveries)
            panelsDeliverys.put(delivery,new DeliveryPanel(delivery));

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        setLayout(new java.awt.GridBagLayout());

        int pos = 0;
        for(Delivery delivery : deliveries){

            gridBagConstraints = new GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = pos;
            gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
            gridBagConstraints.weightx = 0.1;
            gridBagConstraints.weighty = 0.1;
            add(panelsDeliverys.get(delivery),gridBagConstraints);
            pos ++;
        }

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
