package lhexanome.optimodlivraison.ui.netbeanpanel;

import lhexanome.optimodlivraison.platform.models.RoadMap;
import lhexanome.optimodlivraison.ui.component.RoadMapComponent;
import lhexanome.optimodlivraison.ui.netbeanpanel.roadmappreviewlistener.ClickChooseDeliveryOrderListener;

/**
 *
 * @author hugues
 */
public class RoadMapPreviewPanel extends javax.swing.JPanel {

    private final RoadMap roadMap;
    private final IRoadMapPreviewController controller;
    private RoadMapComponent roadMapComponent;

    /**
     * Creates new form MapPreview
     */
    public RoadMapPreviewPanel(RoadMap roadMap, IRoadMapPreviewController controller) {
        this.roadMap = roadMap;
        this.controller = controller;
        roadMapComponent = new RoadMapComponent();
        roadMapComponent.setRoadMap(roadMap);
        initComponents();
        jButton1.addActionListener(new ClickChooseDeliveryOrderListener(controller,this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.OverlayLayout(this));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jButton1.setText("Charger demande de livraison");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(jButton1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel2.add(filler2, gridBagConstraints);

        add(jPanel2);

        add(roadMapComponent);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
